### ISSUE TITLE
zinc-io schedular not found

### ISSUE THREAD

**Issue by 108062138** [stonet-research/systor-confznsplusplus-artifact#15]
As titile, I want to reproduce the experiment ZINC-schedular result in the paper. Then I found that the ZINC-schedular link seems to be expired. The following screen shot shows `404` after I clicked on `zinc-schedular` and `zinc-schedular/README.md` 
|404 for zinc-schedular| 404 for zinc-schedular/README.md|
|---|---|
|![image](https://github.com/user-attachments/assets/6d37e14d-e80d-485a-8235-4401fa18be2b)|![image](https://github.com/user-attachments/assets/76ee1f80-a5a5-4d4d-af92-d77cfea005aa)|

thx for reply

**Comment by Krien** [comment]
Hi @108062138 ,

Thank you for the GitHub issue! I have changed the URLs to [https://github.com/stonet-research/zinc-scheduler/blob/master/README.md](https://github.com/stonet-research/zinc-scheduler/blob/master/README.md). The ZINC scheduler used to be part of this repository, but moved to its own repository recently.

**Comment by 108062138** [comment]
I got it. Thank you so much!
